ALTER TABLE `admin` ADD `access` TEXT NOT NULL;
ALTER TABLE `box` ADD `passive` TEXT NOT NULL;
ALTER TABLE `client` ADD `company` TEXT NOT NULL;
ALTER TABLE `client` ADD `address1` TEXT NOT NULL;
ALTER TABLE `client` ADD `address2` TEXT NOT NULL;
ALTER TABLE `client` ADD `city` TEXT NOT NULL;
ALTER TABLE `client` ADD `state` TEXT NOT NULL;
ALTER TABLE `client` ADD `postcode` TEXT NOT NULL;
ALTER TABLE `client` ADD `country` TEXT NOT NULL;
ALTER TABLE `client` ADD `phone` TEXT NOT NULL;
ALTER TABLE `client` ADD `created` DATE;
ALTER TABLE `client` CHANGE `lastlogin` `lastlogin` DATETIME NOT NULL;
INSERT INTO `config` (`setting`, `value`) VALUES ('country', 'US');
ALTER TABLE `game` ADD `qryport` TEXT NOT NULL;
ALTER TABLE `server` ADD `qryport` TEXT NOT NULL;
UPDATE `box` SET `passive` = 'On';
UPDATE `client` SET `created` = NOW();
UPDATE `game` SET `query` = 'none';
UPDATE `server` SET `query` = 'valve';
UPDATE `config` SET `value` = '1.6.0' WHERE `setting` = 'panelversion';